/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as _layoutRouteImport } from './routes/__layout'
import { Route as _layoutIndexRouteImport } from './routes/__layout/index'

const BoardBoardIDLazyRouteImport = createFileRoute('/board/$boardID')()

const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutIndexRoute = _layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _layoutRoute,
} as any)
const BoardBoardIDLazyRoute = BoardBoardIDLazyRouteImport.update({
  id: '/board/$boardID',
  path: '/board/$boardID',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/board/$boardID.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/board/$boardID': typeof BoardBoardIDLazyRoute
  '/': typeof _layoutIndexRoute
}
export interface FileRoutesByTo {
  '/board/$boardID': typeof BoardBoardIDLazyRoute
  '/': typeof _layoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__layout': typeof _layoutRouteWithChildren
  '/board/$boardID': typeof BoardBoardIDLazyRoute
  '/__layout/': typeof _layoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/board/$boardID' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/board/$boardID' | '/'
  id: '__root__' | '/__layout' | '/board/$boardID' | '/__layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _layoutRoute: typeof _layoutRouteWithChildren
  BoardBoardIDLazyRoute: typeof BoardBoardIDLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/': {
      id: '/__layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _layoutIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/board/$boardID': {
      id: '/board/$boardID'
      path: '/board/$boardID'
      fullPath: '/board/$boardID'
      preLoaderRoute: typeof BoardBoardIDLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface _layoutRouteChildren {
  _layoutIndexRoute: typeof _layoutIndexRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutIndexRoute: _layoutIndexRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _layoutRoute: _layoutRouteWithChildren,
  BoardBoardIDLazyRoute: BoardBoardIDLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
